### ISSUE TITLE
Not Authorized Yet

### ISSUE THREAD

**Issue by DietgerBahn** [ibm-security-intelligence/management#3]
Even with authorizing via the admin user and correct credentials/console IP, the Reference Data Tool is saying "Not Authorized Yet". QRadar version 7.2.4 MR4 Patch5 IF1. Any ideas are appreciated and regards, dietger.bahn@us.ibm.com

**Comment by ibmcraigroberts** [comment]
Could you email me a screenshot of the "console" from the web browser. Use f12 in Chrome to bring it up then I can see what calls are failing etc. 

The API endpoints do not seem to have changed after confirming on a later build (could be a P5 or IF01 issue though).

email is my name with a . between at uk dot ibm dot com

**Comment by ibmcraigroberts** [comment]
Also what are the permission on the account used? 

There is a setting to enable API use in user roles

**Comment by ibmcraigroberts** [comment]
This was an issue with using IE  - this currently is not tested against IE. 

Will add caveat to readme
